# -*- coding: utf-8 -*-
"""YouTube Trends Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GTfworIgmCDoiS2GzvkijnnaxAvJIUQ
"""

import pandas as pd
import numpy as np
# Load data
# 1. Basic info
print(df.info())
# 2. Handle missing values
df.dropna(subset=['category_id','views'],inplace=True)
# 3. Filter out extreme outliers (Numpy)
Q1 = np.percentile(df['views'],25)
Q3 = np.percentile(df['views'],75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df['views'] >= lower_bound) & (df['views'] <= upper_bound)]
# 7. Save cleaned data
df.to_csv('cleaned_data.csv',index=False)
print("Cleaning complete. Shape:",df.shape)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

df = pd.read_csv('../content/GBvideos.csv',on_bad_lines='skip')
# Style
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (12,6)
#....................Plot 1: Top 10 categories by views..........
category_views = df.groupby('category_id')['views'].sum().sort_values(ascending=False).head(10)
plt.bar(category_views.index.astype(str),category_views.values/ 1e6, color='skyblue')
plt.title('Top 10 YouTube Categories by Total Views (Millions)')
plt.xlabel('Category ID')
plt.ylabel('Total Views (Millions)')
plt.tight_layout()

# Create the directory if it doesn't exist
os.makedirs('../images/', exist_ok=True)

plt.savefig('../images/tops_categories.png',dpi=150)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

plt.scatter(sample['likes'],sample['dislikes'],alpha=0.5,c='coral',edgecolors='black')
plt.xscale('log')
plt.yscale('log')
plt.title('Likes vs Dislikes (Log Scale)')
plt.xlabel('Likes')
plt.ylabel('Dislikes')
plt.tight_layout()
plt.savefig('../images/likes_vs_dislikes.png',dpi=150)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# Assuming 'date' column can be interpreted as an hour (e.g., 22.10 -> 22 hour)
# Or replace this with the correct logic to extract 'published_hour' from your data
df['published_hour'] = df['date'].astype(int)

plt.hist(df['published_hour'],bins=24,color='skyblue',edgecolor='black')
plt.title ('When Do Trending Videos Get Published')
plt.xlabel('Hour of Day(0-23)')
plt.ylabel('Number of Videos')
plt.xticks(range(0,24,2))
plt.tight_layout()
plt.savefig('../images/trending_time.png',dpi=150)